config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#show"
  resource :home, only: :show, controller: "home"

  namespace :api do
    namespace :v1 do
      resources :meetings
    end
  end

  resources :locations, only: [:index, :create] do
    collection do
      post :import
    end
  end

  namespace :dashboard do
    root to: "home#show"
  end
end

app/models/address.rb
class Address 
  include Neo4j::ActiveNode
  property :text, type: String
  property :lat, type: String
  property :long, type: String
end

app/models/location.rb
require 'csv'
class Location 
  extend Geocoder::Model::ActiveRecord
  include Neo4j::ActiveNode
  property :address, type: String
  property :latitude, type: Float
  property :longitude, type: Float

  attr_accessor :csv, :skip_gecode
  geocoded_by :address, unless: :skip_gecode
  after_validation :geocode, :if => 'address_changed? && !skip_gecode'

  class << self
    def import params
      # Import from csv
      csv = CSV.table(params[:csv].tempfile)
      return false unless csv.headers.include?(:locations)
      csv.each do |row|
        unless row[:locations].blank?
          5.times{
            l = Location.new address: row[:locations]
            l.valid?
            l.save if l.longitude.present? && l.latitude.present?
            sleep(1)
          }
        end
      end
    end
  end
end

app/models/user.rb
module RoleEnums
  extend ActiveSupport::Concern
  ROLES = { admin: 1, moderator: 2 }
  included do
    ROLES.keys.each do |role|
      s = %{
        def #{role}?
          role == ROLES[role.try(:to_sym)]
        end
        def #{role}!
          update_attribute(:role, role)
        end
      }
      eval(s)
    end
  end
end

class User 
  include Neo4j::ActiveNode
  include RoleEnums
    #
    # Neo4j.rb needs to have property definitions before any validations. So, the property block needs to come before
    # loading your devise modules.
    #
    # If you add another devise module (such as :lockable, :confirmable, or :token_authenticatable), be sure to
    # uncomment the property definitions for those modules. Otherwise, the unused property definitions can be deleted.
    #

     property :username, type: String
     property :facebook_token, type: String
     index :facebook_token

     property :created_at, type: DateTime
     property :updated_at, type: DateTime

     ## Database authenticatable
     property :email, type: String, null: false, default: ""
     index :email

     property :encrypted_password

     ## If you include devise modules, uncomment the properties below.

     ## Rememberable
     property :remember_created_at, type: DateTime
     property :remember_token
     index :remember_token


     ## Recoverable
     property :reset_password_token
     index :reset_password_token
     property :reset_password_sent_at, type: DateTime

     ## Trackable
     property :sign_in_count, type: Integer, default: 0
     property :current_sign_in_at, type: DateTime
     property :last_sign_in_at, type: DateTime
     property :current_sign_in_ip, type:  String
     property :last_sign_in_ip, type: String

     ## Confirmable
     # property :confirmation_token
     # index :confirmation_token
     # property :confirmed_at, type: DateTime
     # property :confirmation_sent_at, type: DateTime

     ## Lockable
     #  property :failed_attempts, type: Integer, default: 0
     # property :locked_at, type: DateTime
     #  property :unlock_token, type: String,
     # index :unlock_token

      ## Token authenticatable
      # property :authentication_token, type: String, null: true, index: :exact

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable



  property :role, default: 2
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ApplicationController

end

app/controllers/api/v1/meetings_controller.rb
class Api::V1::MeetingsController < Api::V1::BaseController

  def index
    http = Curl.post("https://api.zoom.us/v1/meeting/live", {api_key: ENV["api_key"], api_secret: ENV["api_secret"]})
    @meetings = JSON.parse(http.body)
    http = Curl.post("https://api.zoom.us/v1/meeting/live", {api_key: ENV["api_key"], api_secret: ENV["api_secret"]})
    @live_meetings = JSON.parse(http.body)
  end

  def create
    http = Curl.post("https://api.zoom.us/v1/meeting/create", {api_key: ENV["api_key"], api_secret: ENV["api_secret"], host_id: ENV["host_id"], topic: params["topic"], type: 1, password: params["password"]})
    meeting = JSON.parse(http.body)
    redirect_to api_v1_meeting_path(method: :get, id: meeting["id"])
  end

  def show
    http = Curl.post("https://api.zoom.us/v1/meeting/get", {api_key: ENV["api_key"], api_secret: ENV["api_secret"], host_id: ENV["host_id"], id: params["id"]})
    @meeting = JSON.parse(http.body)
  end

  def destroy
    http = Curl.post("https://api.zoom.us/v1/meeting/end", {api_key: ENV["api_key"], api_secret: ENV["api_secret"], host_id: ENV["host_id"], id: params["id"]})
    redirect_to api_v1_meetings_path
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception
  after_action :verify_authorized, except: :index, unless: :devise_controller?
  #   before_action :verify_authorized, except: :index, unless: :devise_controller?

  after_action :verify_policy_scoped, :only => :index

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/dashboard/home_controller.rb
module Dashboard
  class HomeController < DashboardController
    # "Mohan::#{self.class.name}".deconstantize.underscore
    # output -> mohan/dashboard
    def show
      authorize :"#{params[:controller]}", :show?
    end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
    authorize :"#{params[:controller]}", :show?
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def create
  end

  def import
    @location = Location.import permitted_attributes(Location.new)
    authorize Location.new
    if @location
      redirect_to action: :index
    else
      flash[:error] = "Unable to import"
      redirect_to action: :index
    end
  end

  def index
    @location = Location.new if policy(:location).import?
    @locations = policy_scope(Location)
    respond_to do |format|
      format.json
      format.html
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade in") do 
              concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
              concat message 
            end)
    end
    nil
  end
end

app/helpers/dashboard/home_helper.rb
module Dashboard::HomeHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/dashboard/home/show.html.slim
= content_for :javascripts do
  = javascript_include_tag "dashboard/home", 'data-turbolinks-track' => true

h1 Voila

app/views/home/show.html.slim
h1 Home/Landing page content

app/views/layouts/_footer.html.slim
footer.footer
  .container
    p.text-muted Place sticky footer content here.

app/views/layouts/_header.html.slim
nav.navbar.navbar-default.navbar
  .container
    .navbar-header
      button.navbar-toggle.collapsed aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" type="button" 
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      a.navbar-brand href="#"  Neo4JDemo
    #navbar.collapse.navbar-collapse
      ul.nav.navbar-nav
        li.active
          a href="#"  Home
        li
          a href="#about"  About
        li
          a href="#contact"  Contact
        li.dropdown
          a.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button" 
            | Dropdown
            span.caret
          ul.dropdown-menu
            li
              a href="#"  Action
            li
              a href="#"  Another action
            li
              a href="#"  Something else here
            li.divider role="separator" 
            li.dropdown-header Nav header
            li
              a href="#"  Separated link
            li
              a href="#"  One more separated link
      - if user_signed_in?
        ul.nav.navbar-nav.pull-right
          li
            = link_to "Sign out", destroy_user_session_path, method: :delete
      - else
        ul.nav.navbar-nav.pull-right
          li
            = link_to "Sign in", new_user_session_path

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title Neo4jRailsSample
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = yield(:stylesheets)
    = csrf_meta_tags
  body
    = render 'layouts/header'
    .container
      = flash_messages
      = yield
    / = render 'layouts/footer'
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = yield :javascripts

app/views/layouts/dashboard.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title Neo4jRailsSample Dashboard
    = stylesheet_link_tag    'dashboard', media: 'all', 'data-turbolinks-track' => true
    = yield(:stylesheets)
    = csrf_meta_tags
  body
    = render 'layouts/header'
    .container
      = flash_messages
      = yield
    = render 'layouts/footer'
    = javascript_include_tag 'dashboard', 'data-turbolinks-track' => true
    = yield :javascripts

app/views/locations/_form.html.slim
= simple_form_for(location, url: import_locations_path, html: { class: 'form-horizontal' }) do |form|
  = form.input :csv, as: :file, input_html: { class: "form-control" }
  = form.button :submit, "Upload CSV", input_html: { class: "form-control"}

app/views/locations/index.html.slim
- if policy(:location).import?
  = render "locations/form", location: @location
- data = render template: "locations/index.json.jbuilder", formats: [:json], locals: { locations: @locations, format: :json }
- data = raw(data.html_safe);

#map

= content_for :javascripts do
  javascript:
    var map, heatmap;

    function initMap() {
      map = new google.maps.Map(document.getElementById('map'), {
        zoom: 13,
        center: {lat: 17.3850, lng: 78.4867},
        mapTypeId: google.maps.MapTypeId.SATELLITE
      });

      heatmap = new google.maps.visualization.HeatmapLayer({
        maxWeight: 3,
        data: getPoints(),
        map: map
      });
    }

    getPoints = function(){
      a = #{data}
      results = []
      for(i=0;i<a.locations.length; i++)
        results.push({ location: new google.maps.LatLng(a.locations[i][0], a.locations[i][1]), weight: 3 })
      return results
    }

  = javascript_include_tag "http://maps.googleapis.com/maps/api/js?key=AIzaSyCoioYO_CSi0zR3H5I5Ze3ME_InxLgf7h8&libraries=visualization&callback=initMap"